name: hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "Hello world"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Use gcloud CLI
        run: gcloud config list

      - name: deploy cloud function
        run: |
          gcloud functions deploy cfr_test \
            --runtime python311 \
            --trigger-bucket cfr_test \
            --region asia-northeast1 \
            --entry-point main \
            --source ./cloudfunctions/aa